# Each new term in the Fibonacci sequence is generated by 
# adding the # previous two terms. By starting with 1 and 2, 
# the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose 
# values do not # exceed four million, find the sum of 
# the even-valued terms.

# Ustvarimo seznam Fibonaccijevih stevil.
fibonacci = list ( )
fibonacci.append ( 1 )
fibonacci.append ( 2 )

#Zanimajo nas Fibonaccijeva stevila pod 4000000.
s = 1
while s < 4000000:
    s =  fibonacci [ - 1 ] + fibonacci [ - 2 ]
    if s < 4000000:
        fibonacci.append ( s )
    else:
        pass


even_fibonacci = list(stevilo for stevilo in fibonacci if stevilo % 2 == 0)

print(even_fibonacci)

vsota = sum ( stevilo for stevilo in even_fibonacci )
print ( vsota ) 